### ISSUE TITLE
Source

### ISSUE THREAD

**Issue by MatSpy** [dreamz12345/Python-Projects#1]
Hello.

I am learning python too. Nice work.  I was looking around for good Python course. I suppose your code is based on some book. Can you tell me what title of this book is? Your code looks perfect. 

It would be nice to have this information in readme. 

Thanks in advance for answer.
Regards.
Mateusz

**Comment by dreamz12345** [comment]
Hi,

Thanks for kind words. My code is based on online course I bought on udemy.com
I added all of the info to README file. You can find there course name and link to it.
I also get weekly tutoring with Senior Developer so your expirience with this course might be
different from mine. Nevertheless, I highly recommend checking it since there's a lot of 
usefull informations and the course was really affordable.

Good luck with your studies.
Cheers,
Lukasz

**Comment by mateusz-spychala** [comment]
Nice,
thanks. 
Issue can be closed.
